# Basic `dependabot.yml` file with Dockerfile updates

version: 2
updates:
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `go-demo` directory
    directory: "/go-demo"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "docker"
        versions: ["1.24", "1.25", "2.x"]
