services:
  web:
    build: .
    image: go-demo
    pull_policy: never
    environment:
      POSTGRES_DSN: postgres://user:password@postgres:5432/test?sslmode=disable
      REDIS_ADDR: "redis:6379"
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d test"]
      interval: 5s
      timeout: 5s
      retries: 20
